<?php
// Tableau des destinations
$destinations = [
    [
        'id' => 1,
        'type' => 'hotel',
        'nom' => 'Hôtel Hilton',
        'ville' => 'Yaoundé',
        'pays' => 'Cameroun',
        'note' => '8.5 Superbe',
        'experiences' => '120 expériences vécues',
        'prix' => '$50,00',
        'image' => 'images/hotel_hilton.png',
        'lien' => 'description.php?id=1' // Lien dynamique
    ],
    [
        'id' => 2,
        'type' => 'hotel',
        'nom' => 'Hôtel United',
        'ville' => 'Yaoundé',
        'pays' => 'Cameroun',
        'note' => '7.5 Superbe',
        'experiences' => '120 expériences vécues',
        'prix' => '$50,00',
        'image' => 'images/united_hotel.png',
        'lien' => 'description.php?id=2' // Lien dynamique
    ],
    [
        'id' => 3,
        'type' => 'hotel',
        'nom' => 'La Vallé de Bana',
        'ville' => 'Bana',
        'pays' => 'Cameroun',
        'note' => '9.5 Superbe',
        'experiences' => '200 expériences vécues',
        'prix' => '$50,00',
        'image' => 'images/La_Valle_De_Bana.png',
        'lien' => 'description.php?id=3' // Lien dynamique
    ],
    [
        'id' => 4,
        'type' => 'hotel',
        'nom' => 'Onomo Hôtel',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '7 Superbe',
        'experiences' => '200 expériences vécues',
        'prix' => '$40,00',
        'image' => 'images/Onomo_hotel.png',
        'lien' => 'description.php?id=4' // Lien dynamique
    ],
    [
        'id' => 5,
        'type' => 'hotel',
        'nom' => 'Hôtel residence la falaise',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '7.3 Superbe',
        'experiences' => '200 expériences vécues',
        'prix' => '$40,00',
        'image' => 'images/Hotel_la_falaise.png',
        'lien' => 'description.php?id=5' // Lien dynamique
    ],
    [
        'id' => 5,
        'type' => 'restaurant',
        'nom' => 'The Yard',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '9.0 Excellent',
        'experiences' => '85 expériences vécues',
        'prix' => '$20,00',
        'image' => 'images/the_yard.png',
        'lien' => 'description.php?id=6' // Lien dynamique
    ],
    [
        'id' => 6,
        'type' => 'restaurant',
        'nom' => 'Kotcha Restaurant',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '9.0 Excellent',
        'experiences' => '85 expériences vécues',
        'prix' => '$20,00',
        'image' => 'images/Kotcha_Restaurant.jpg',
        'lien' => 'description.php?id=7' // Lien dynamique
    ],
    [
        'id' => 7,
        'type' => 'restaurant',
        'nom' => 'Deido 50 Nuances De Grey',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '9.0 Excellent',
        'experiences' => '85 expériences vécues',
        'prix' => '$20,00',
        'image' => 'images/Deido_50_Nuances_De_Grey.png',
        'lien' =>'description.php?id=8' // Lien dynamique
    ],
    [
        'id' => 8,
        'type' => 'restaurant',
        'nom' => 'Saga Africa',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '9.0 Excellent',
        'experiences' => '85 expériences vécues',
        'prix' => '$20,00',
        'image' => 'images/Saga_Africa.png',
        'lien' => 'description.php?id=9' // Lien dynamique
    ],
    [
        'id' => 9,
        'type' => 'festival',
        'nom' => 'Le Festival du Ngond',
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '8.0 Très bien',
        'experiences' => '200 expériences vécues',
        'prix' => '$10,00',
        'image' => 'images/Ngondo.png',
        'lien' => 'description.php?id=10' // Lien dynamique
    ],
    [
        'id' => 10,
        'type' => 'festival',
        'nom' => 'Le Festival des Elog Mpoo',
        'ville' => 'Edéa',
        'pays' => 'Cameroun',
        'note' => '8.0 Très bien',
        'experiences' => '200 expériences vécues',
        'prix' => '$10,00',
        'image' => 'images/Elog_Mpoo.png',
        'lien' => 'description.php?id=11' // Lien dynamique
    ],
    [
        'id' => 11,
        'type' => 'festival',
        'nom' => 'Le Festival Nyem Nyem',
        'ville' => 'Ngaoundere',
        'pays' => 'Cameroun',
        'note' => '8.0 Très bien',
        'experiences' => '200 expériences vécues',
        'prix' => '$10,00',
        'image' => 'images/Nyem_Nyem.png',
        'lien' => 'description.php?id=11' // Lien dynamique
    ],
    [
        'id' => 12,
        'type' => 'festival',
        'nom' => 'Le Festival du peuple Batanga',
        'ville' => 'Kribi',
        'pays' => 'Cameroun',
        'note' => '8.0 Très bien',
        'experiences' => '200 expériences vécues',
        'prix' => '$10,00',
        'image' => 'images/batanga.png',
        'lien' => 'description.php?id=12' // Lien dynamique
    ],
    [
        'id' => 13,
        'type' => 'site-touristique',
        'nom' => 'Mont Cameroun',
        'ville' => 'Limbe',
        'pays' => 'Cameroun',
        'note' => '9.5 Exceptionnel',
        'experiences' => '300 expériences vécues',
        'prix' => '$5,00',
        'image' => 'images/mont_cameroun.png',
        'lien' => 'description.php?id=13' // Lien dynamique
    ],
    [
        'id' => 14,
        'type' => 'site-touristique',
        'nom' => "Cascades d'Ekom Nkam",
        'ville' => 'Douala',
        'pays' => 'Cameroun',
        'note' => '9.5 Exceptionnel',
        'experiences' => '300 expériences vécues',
        'prix' => '$5,00',
        'image' => "images/Cascades_d'Ekom_Nkam.jpg",
        'lien' => 'description.php?id=14' // Lien dynamique
    ],
    [
        'id' => 15,
        'type' => 'site-touristique',
        'nom' => 'Limbe Botanic Garden',
        'ville' => 'Limbe',
        'pays' => 'Cameroun',
        'note' => '9.5 Exceptionnel',
        'experiences' => '300 expériences vécues',
        'prix' => '$5,00',
        'image' => 'images/Limbe_Botanic_Garden.jpg',
        'lien' => 'description.php?id=15' // Lien dynamique
    ],
    [
        'id' => 16,
        'type' => 'site-touristique',
        'nom' => 'Limbe Wildlife Centre',
        'ville' => 'Limbe',
        'pays' => 'Cameroun',
        'note' => '9.5 Exceptionnel',
        'experiences' => '300 expériences vécues',
        'prix' => '$5,00',
        'image' => 'images/Limbe_Wildlife_Centre.jpg',
        'lien' => 'description.php?id=16' // Lien dynamique
    ],
    // Ajoutez d'autres destinations ici
];
?>